export const data = [
  {
    subject: "English",
    nameOfTeacher: "Temidayo Kukoyi",
    examDate: "April 10th",
    dayTime: "Monday",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Mathematics",
    nameOfTeacher: "James Ubong",
    examDate: "April 11th",
    dayTime: "Tuesday",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Home Economics",
    nameOfTeacher: "Janet Iron",
    examDate: "April 10th",
    dayTime: "Monday",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "French",
    nameOfTeacher: "Oladipupo Bori ",
    examDate: "April 17th",
    dayTime: "Monday",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Biology",
    nameOfTeacher: "Towode Ayodele",
    examDate: "April 19th",
    dayTime: "Wednesday",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Physics",
    nameOfTeacher: "Chika Nwene",
    examDate: "April 12th",
    dayTime: "Wednesday",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Commerce",
    nameOfTeacher: "Danjuma Iyare",
    examDate: "April 14th",
    dayTime: "Friday",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Account",
    nameOfTeacher: "Ireti Osayemi",
    examDate: "April 19th",
    dayTime: "Wednesday",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "History",
    nameOfTeacher: "Jesicca Bukola",
    examDate: "April 20th",
    dayTime: "Thursday",
    status: "Rejected",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Government",
    nameOfTeacher: "James Adeyemi",
    examDate: "April 18th",
    dayTime: "Tuesday",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Literature",
    nameOfTeacher: "Tola Cregx",
    examDate: "April 14th",
    dayTime: "Friday",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "CRK/IRK",
    nameOfTeacher: "Pemi Mayowa",
    examDate: "April 13th",
    dayTime: "Wednesday",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
];

export default data;
