export const data = [
  {
    name: `Temidayo Kukoyi `,
    matricNumber: "BC39635",
    level: "200",
    department: "Chemical Science",
    course: "Biochemistry",
    mark: "65",
    grade: "B",
    status: "Compulsory",
  },
  {
    name: `James Ubong`,
    matricNumber: "CS70668",
    level: "200",
    department: "Chemical Science",
    course: "Biochemistry",
    mark: "78",
    grade: "A",
    status: "Compulsory",
  },
  {
    name: `Janet Iron `,
    matricNumber: "ZY97174",
    level: "200",
    department: "Chemical Science",
    course: "Biochemistry",
    mark: "32",
    grade: "E",
    status: "Compulsory",
  },
  {
    name: `Oladipupo Bori `,
    matricNumber: "MD97174",
    level: "300",
    department: "Chemical Science",
    course: "Biochemistry",
    mark: "28",
    grade: "E",
    status: "Compulsory",
  },
  {
    name: `Towode Ayodele `,
    matricNumber: "AG43178",
    level: "400",
    department: "Chemical Science",
    course: "Biochemistry",
    mark: "90",
    grade: "A",
    status: "Compulsory",
  },
  {
    name: `Temidayo Kukoyi `,
    matricNumber: "BA22739",
    level: "300",
    department: "Chemical Science",
    course: "Biochemistry",
    mark: "80",
    grade: "A",
    status: "Compulsory",
  },
  {
    name: `Danjuma Iyare `,
    matricNumber: "MB227395",
    level: "300",
    department: "Chemical Science",
    course: "Biochemistry",
    mark: "80",
    grade: "A",
    status: "Compulsory",
  },
  {
    name: `Ireti Isayemi `,
    matricNumber: "IC39635",
    level: "300",
    department: "Chemical Science",
    course: "Biochemistry",
    mark: "18",
    grade: "F",
    status: "Compulsory",
  },
  {
    name: `Jesicca Bukola `,
    matricNumber: "BC39635",
    level: "200",
    department: "Chemical Science",
    course: "Biochemistry",
    mark: "20",
    grade: "F",
    status: "Elective",
  },
  {
    name: `James Adeyemi `,
    matricNumber: "AT70668",
    level: "200",
    department: "Chemical Science",
    course: "Biochemistry",
    mark: "58",
    grade: "C",
    status: "Compulsory",
  },
  {
    name: `Tola Cregx `,
    matricNumber: "CS97174",
    level: "300",
    department: "Chemical Science",
    course: "Biochemistry",
    mark: "45",
    grade: "D",
    status: "Compulsory",
  },
  {
    name: `Pem Mayowa `,
    matricNumber: "AS43178",
    level: "300",
    department: "Chemical Science",
    course: "Biochemistry",
    mark: "98",
    grade: "A",
    status: "Compulsory",
  },
];

export default data;
