export const data = [
  {
    courseName: "Molecular Biology",
    courseCode: `BCH 312 `,
    lecturer: "Daniel Steward",
    department: "Chemical Sciences",
    unit: "2",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseName: "Computer Programming",
    courseCode: `CSC 204`,
    lecturer: "Floyd Miles",
    department: "Mathematical Science",
    unit: "3",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseName: "Molecular Biology",
    courseCode: `BCH 208 `,
    lecturer: "Wade Warren",
    department: "Biological Science",
    unit: "3",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseName: "Computer Programming",
    courseCode: `CSC 402`,
    lecturer: "Courtney Henry ",
    department: "Mathematical Science",
    unit: "2",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseName: "Compiling Techniques",
    courseCode: ` CSC 431`,
    lecturer: "Wade Warren",
    department: "Mathematical Science",
    unit: "1",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseName: "Organic Chemistry",
    courseCode: ` CHM 302`,
    lecturer: "Darrel Steward",
    department: "Chemical Science",
    unit: "6",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseName: "Genetics",
    courseCode: ` MCB 402`,
    lecturer: "Darrel Steward",
    department: "Biological Science",
    unit: "3",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseName: "Cell Biology",
    courseCode: ` BCH 504`,
    lecturer: "Darrel Steward",
    department: "Industrial Chemistry",
    unit: "2",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseName: "Coding",
    courseCode: `CSC 202`,
    lecturer: "Eleanor Pena",
    department: "Mathematical Science",
    unit: "2",
    status: "Rejected",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseName: "Industrial Chemistry",
    courseCode: ` CHM 407`,
    lecturer: "Bessie Cooper",
    department: "Chemical Science",
    unit: "2",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseName: "Chemistry",
    courseCode: `CHM 212 `,
    lecturer: "Dianne Russell",
    department: "Chemical Science",
    unit: "3",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseName: "Enzymology",
    courseCode: `BCH 301 `,
    lecturer: "Robert Fox",
    department: "Medical",
    unit: "1",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
];

export default data;
