export const data = [
  {
    name: `Temidayo Kukoyi `,
    studentId: "39635",
    classData: "SS3",
    mark: "65",
    grade: "B",
    position: "5th",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `James Ubong`,
    studentId: "70668",
    classData: "JS2",
    mark: "78",
    grade: " A",
    position: "4th",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Janet Iron `,
    studentId: "97174",
    classData: "JS3",
    mark: "32",
    grade: "E",
    position: "8th",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Oladipupo Bori `,
    studentId: "97174",
    classData: "SS2",
    mark: "28",
    grade: "E",
    position: "9th",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Towode Ayodele `,
    studentId: "43178",
    classData: "JS1",
    mark: "90",
    grade: "A",
    position: "2nd",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Temidayo Kukoyi `,
    studentId: "22739",
    classData: "JS2",
    mark: "80",
    grade: "A",
    position: "3rd",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Danjuma Iyare `,
    studentId: "227395",
    classData: "SS3",
    mark: "20",
    grade: "F",
    position: "10th",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Ireti Isayemi `,
    studentId: "39635",
    classData: "SS1",
    mark: "58",
    grade: "C",
    position: "6th",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Jesicca Bukola `,
    studentId: "39635",
    classData: "JS1",
    mark: "45",
    grade: "D",
    position: "7th",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `James Adeyemi `,
    studentId: "70668",
    classData: "JS1",
    mark: "18",
    grade: "F",
    position: "11th",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Tola Cregx `,
    studentId: "97174",
    classData: "SS2",
    mark: "98",
    grade: "A",
    position: "1st",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
];

export default data;
