export const data = [
  {
    course: "Biochemistry",
    courseCode: `BCH201 `,
    lecturer: "Temidayo Kukoyi",
    status: "Pending",
    department: "Chemical Sciences",
    unit: "2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    course: "Introduction to Enzyme",
    courseCode: `BCH205`,
    lecturer: "James Ubong",
    status: "Approved",
    department: "Mathematical Sciences",
    unit: "3",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    course: "Catalyst",
    courseCode: `BCH207 `,
    lecturer: "Janet Iron",
    status: "Pending",
    department: "Biological Science",
    unit: "3",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    course: "Nutrition",
    courseCode: `BCH209`,
    lecturer: "Oladipupo Bori ",
    status: "Approved",
    department: "Medical Science",
    unit: "2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    course: "Experimental Biochemistry",
    courseCode: ` BCH211`,
    lecturer: "Towode Ayodele",
    status: "Pending",
    department: "Agriculture",
    unit: "1",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    course: "Carbohydrates",
    courseCode: ` BCH213`,
    lecturer: "Chika Nwene",
    status: "Approved",
    department: "Management",
    unit: "6",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    course: "Cell Biology",
    courseCode: ` MCB201`,
    lecturer: "Danjuma Iyare",
    status: "Pending",
    department: "Chemical Sciences",
    unit: "3",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    course: "Molecular Genetics",
    courseCode: ` MCB203`,
    lecturer: "Ireti Osayemi",
    status: "Approved",
    department: "Chemical Sciences",
    unit: "2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    course: "Neurobiology",
    courseCode: `MCB205`,
    lecturer: "Jesicca Bukola",
    status: "Rejected",
    department: "Management",
    unit: "2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    course: "Chromosomes",
    courseCode: ` MCB207`,
    lecturer: "James Adeyemi",
    status: "Approved",
    department: "Social Science",
    unit: "2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    course: "Biochemistry of Membranes",
    courseCode: `MCB209 `,
    lecturer: "Tola Cregx",
    status: "Approved",
    department: "Engineering",
    unit: "3",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    course: "Q Basic",
    courseCode: `CSC101 `,
    lecturer: "Pem Mayowa",
    status: "Approved",
    department: "Art",
    unit: "1",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
];

export default data;
