export const data = [
  {
    courseCode: `BCH201 `,
    courseTitle: "Introduction to Biochemistry",
    nameOfLecturer: "Temidayo Kukoyi",
    students: "79",
    unit: "2",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseCode: `BCH205`,
    courseTitle: "Introduction to Enzyme",
    nameOfLecturer: "James Ubong",
    students: "70",
    unit: "3",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseCode: `BCH207 `,
    courseTitle: "Catalyst",
    nameOfLecturer: "Janet Iron",
    students: "79",
    unit: "3",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseCode: `BCH209`,
    courseTitle: "Nutrition",
    nameOfLecturer: "Oladipupo Bori ",
    students: "68",
    unit: "2",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseCode: ` BCH211`,
    courseTitle: "Experimental Biochemistry",
    nameOfLecturer: "Towode Ayodele",
    students: "56",
    unit: "1",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseCode: ` BCH213`,
    courseTitle: "Carbohydrates",
    nameOfLecturer: "Chika Nwene",
    students: "85",
    unit: "6",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseCode: ` MCB201`,
    courseTitle: "Cell Biology",
    nameOfLecturer: "Danjuma Iyare",
    students: "68",
    unit: "3",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseCode: ` MCB203`,
    courseTitle: "Molecular Genetics",
    nameOfLecturer: "Ireti Osayemi",
    students: "74",
    unit: "2",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseCode: `MCB205`,
    courseTitle: "Neurobiology",
    nameOfLecturer: "Jesicca Bukola",
    students: "70",
    unit: "2",
    status: "Rejected",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseCode: ` MCB207`,
    courseTitle: "Chromosomes",
    nameOfLecturer: "James Adeyemi",
    students: "65",
    unit: "2",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseCode: `MCB209 `,
    courseTitle: "Biochemistry of Membranes",
    nameOfLecturer: "Tola Cregx",
    students: "68",
    unit: "3",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    courseCode: `CSC101 `,
    courseTitle: "Q Basic",
    nameOfLecturer: "Pem Mayowa",
    students: "71",
    unit: "1",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
];

export default data;
