export const data = [
  {
    name: `Temidayo Kukoyi `,
    matricNumber: "BC39635",
    email: "tem6278@gmail.com",
    level: "100",
    course: "Biochemistry",
    cgpa: "3.2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `James Ubong`,
    matricNumber: "CS70668",
    email: "james278@gmail.com",
    level: "200",
    course: "Computer Science",
    cgpa: "4.5",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Janet Iron `,
    matricNumber: "ZY97174",
    email: "janetiron@gmail.com",
    level: "100",
    course: "Zoology",
    cgpa: "1.2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Oladipupo Bori `,
    matricNumber: "MD97174",
    email: "oladipupo678@gmail.com",
    level: "300",
    course: "Medicine",
    cgpa: "2.4",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Towode Ayodele `,
    matricNumber: "AG43178",
    email: "towodeleayo@gmail.com",
    level: "200",
    course: "Agric Econonmics",
    cgpa: "4.7",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Temidayo Kukoyi `,
    matricNumber: "BA22739",
    email: "chikanwene55@gmail.com",
    level: "400",
    course: "Business Admin",
    cgpa: "3.4",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Danjuma Iyare `,
    matricNumber: "MB227395",
    email: "danjuma@gmail.com",
    level: "500",
    course: "Microbiology",
    cgpa: "1.3",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Ireti Isayemi `,
    matricNumber: "IC39635",
    email: "iretiosayemi457@gmail.com",
    level: "100",
    course: "Industrial Chemistry",
    cgpa: "2.3",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Jesicca Bukola `,
    matricNumber: "BC39635",
    email: "jesicabukky@gmail.com",
    level: "200",
    course: "Archaelogy",
    cgpa: "4.2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `James Adeyemi `,
    matricNumber: "AT70668",
    email: "jamesadeyemi@gmail.com",
    level: "100",
    course: "Architecture",
    cgpa: "1.9",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Tola Cregx `,
    matricNumber: "CS97174",
    email: "tolacregx@gmail.com",
    level: "200",
    course: "Celtic Studies",
    cgpa: "3.2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Pem Mayowa `,
    matricNumber: "AS43178",
    email: "mayowapem@gmail.com",
    level: "100",
    course: "Accounting & Finance",
    cgpa: "3.2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
];

export default data;
