export const data = [
  {
    name: `Temidayo Kukoyi `,
    studentId: "39635",
    classData: "SS2",
    department: "Art",
    course: "English",
    cgpa: "3.2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `James Ubong`,
    studentId: "70668",
    classData: "SS2",
    department: "Science",
    course: " English",
    cgpa: "4.5",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Janet Iron `,
    studentId: "97174",
    classData: "SS2",
    department: "Science",
    course: "English",
    cgpa: "1.2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Oladipupo Bori `,
    studentId: "97174",
    classData: "SS2",
    department: "Science",
    course: "English",
    cgpa: "2.4",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Towode Ayodele `,
    studentId: "43178",
    classData: "SS2",
    department: "Art",
    course: "English",
    cgpa: "4.7",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Temidayo Kukoyi `,
    studentId: "22739",
    classData: "SS2",
    department: "Art",
    course: "English",
    cgpa: "3.4",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Danjuma Iyare `,
    studentId: "227395",
    classData: "SS2",
    department: "Science",
    course: "English",
    cgpa: "1.3",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Ireti Isayemi `,
    studentId: "39635",
    classData: "SS2",
    department: "Science",
    course: "English",
    cgpa: "2.3",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Jesicca Bukola `,
    studentId: "39635",
    classData: "SS2",
    department: "Art",
    course: "English",
    cgpa: "4.2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `James Adeyemi `,
    studentId: "70668",
    classData: "SS2",
    department: "Art",
    course: "English",
    cgpa: "1.9",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Tola Cregx `,
    studentId: "97174",
    classData: "SS2",
    department: "Science",
    course: "English",
    cgpa: "3.2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Pem Mayowa `,
    studentId: "43178",
    classData: "SS2",
    department: "Art",
    course: "English",
    cgpa: "3.2",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
];

export default data;
