export const data = [
  {
    subject: "English",
    nameOfTeacher: "Temidayo Kukoyi",
    students: "79",
    unit: "2",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Mathematics",
    nameOfTeacher: "James Ubong",
    students: "70",
    unit: "3",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Home Economics",
    nameOfTeacher: "Janet Iron",
    students: "79",
    unit: "3",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "French",
    nameOfTeacher: "Oladipupo Bori ",
    students: "68",
    unit: "2",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Biology",
    nameOfTeacher: "Towode Ayodele",
    students: "56",
    unit: "1",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Physics",
    nameOfTeacher: "Chika Nwene",
    students: "85",
    unit: "6",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Commerce",
    nameOfTeacher: "Danjuma Iyare",
    students: "68",
    unit: "3",
    status: "Pending",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Account",
    nameOfTeacher: "Ireti Osayemi",
    students: "74",
    unit: "2",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "History",
    nameOfTeacher: "Jesicca Bukola",
    students: "70",
    unit: "2",
    status: "Rejected",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Government",
    nameOfTeacher: "James Adeyemi",
    students: "65",
    unit: "2",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "Literature",
    nameOfTeacher: "Tola Cregx",
    students: "68",
    unit: "3",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
  {
    subject: "CRK/IRK",
    nameOfTeacher: "Pem Mayowa",
    students: "71",
    unit: "1",
    status: "Approved",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
  },
];

export default data;
