export const data = [
    {
      courseName: `Introduction to Computer Science`,
      courseCode: "CSC 211",
      level: "200",
      students: "79",
      department: "Computer Science",
      unit: "2",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      courseName: `Introduction to Computer Programming`,
      courseCode: "CSC 214",
      level: "200",
      students: "70",
      department: "Computer Science",
      unit: "3",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      courseName: `Computer Programming`,
      courseCode: "CSC 224",
      level: "200",
      students: "79",
      department: "Computer Science",
      unit: "3",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      courseName: `Computer Networking`,
      courseCode: "CSC 312",
      level: "300",
      students: "68",
      department: "Computer Science",
      unit: "2",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      courseName: `Compiling Techniques`,
      courseCode: "CSC 431",
      level: "400",
      students: "56",
      department: "Computer Science",
      unit: "1",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      courseName: `Python`,
      courseCode: "CHM 312",
      level: "300",
      students: "65",
      department: "Computer Science",
      unit: "6",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      courseName: `Algorithms`,
      courseCode: "CSC 324",
      level: "300",
      students: "68",
      department: "Computer Science",
      unit: "3",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      courseName: `Computer Architecture`,
      courseCode: "BCM 314",
      level: "300",
      students: "74",
      department: "Computer Science",
      unit: "2",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      courseName: `Coding`,
      courseCode: "CSC 212",
      level: "200",
      students: "70",
      department: "Computer Science",
      unit: "2",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      courseName: `Computer Engineering`,
      courseCode: "CSC 324",
      level: "300",
      students: "65",
      department: "Computer Science",
      unit: "2",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      courseName: `Coding`,
      courseCode: "CSC 324",
      level: "300",
      students: "68",
      department: "Computer Science",
      unit: "3",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      courseName: `Web Development`,
      courseCode: "CSC 425",
      level: "400",
      students: "71",
      department: "Computer Science",
      unit: "1",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
  ];
  
  export default data;
  