export const data = [
    {
      name: `Temidayo Kukoyi `,
      matricNumber: "BC39635",
      level: "100",
      department: "Computer Science",
      course: "Computer Sciene",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `James Ubong`,
      matricNumber: "CS70668",
      level: "100",
      department: "Computer Science",
      course: "Computer Sciene",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Janet Iron `,
      matricNumber: "ZY97174",
      level: "100",
      department: "Computer Science",
      course: "Computer Sciene",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Oladipupo Bori `,
      matricNumber: "MD97174",
      level: "100",
      department: "Computer Science",
      course: "Computer Sciene",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Towode Ayodele `,
      matricNumber: "AO43178",
      level: "200",
      department: "Computer Science",
      course: "Computer Sciene",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Temidayo Kukoyi `,
      matricNumber: "BA22739",
      level: "100",
      department: "Computer Science",
      course: "Computer Sciene",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Danjuma Iyare `,
      matricNumber: "MB22735",
      level: "100",
      department: "Computer Science",
      course: "Computer Sciene",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Ireti Isayemi `,
      matricNumber: "IC39635",
      level: "100",
      department: "Computer Science",
      course: "Mathematics",
      status: "Elective",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Jesicca Bukola `,
      matricNumber: "BC39635",
      email: "jesicabukky@gmail.com",
      level: "100",
      department: "Computer Science",
      course: "Computer Sciene",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `James Adeyemi `,
      matricNumber: "AT70668",
      level: "200",
      department: "Computer Science",
      course: "Computer Sciene",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Tola Cregx `,
      matricNumber: "CS97174",
      level: "100",
      department: "Computer Science",
      course: "Computer Sciene",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Pem Mayowa `,
      matricNumber: "AS43178",
      level: "100",
      department: "Computer Science",
      course: "Statistics",
      status: "Elective",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
  ];
  
  export default data;
  