export const data = [
  {
    name: `Temidayo Kukoyi `,
    staffID: "43756",
    email: "tem6278@gmail.com",
    level: "Senior Lecturer",
    department: "Chemical Sciences",
    course: "Biochemistry",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `James Ubong`,
    staffID: "43178",
    email: "james278@gmail.com",
    level: "Lecturer 2",
    department: "Mathematical Sciences",
    course: "Computer Science",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Janet Iron `,
    staffID: "43756",
    email: "janetiron@gmail.com",
    level: "Senior Lecturer",
    department: "Biological Sciences",
    course: "Zoology",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Oladipupo Bori `,
    staffID: "22739",
    email: "oladipupo678@gmail.com",
    level: "3Professor",
    department: "Medical Science",
    course: "Medicine",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Towode Ayodele `,
    staffID: "70668",
    email: "towodeleayo@gmail.com",
    level: "Associate Professor",
    department: "Agriculture",
    course: "Agric Econonmics",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Temidayo Kukoyi `,
    staffID: "43756",
    email: "chikanwene55@gmail.com",
    level: "Lecturer 2",
    department: "Managment",
    course: "Business Admin",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Danjuma Iyare `,
    staffID: "70658",
    email: "danjuma@gmail.com",
    level: "Professor",
    department: "Chemical Sciences",
    course: "Microbiology",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Ireti Isayemi `,
    staffID: "39635",
    email: "iretiosayemi457@gmail.com",
    level: "Lecturer 2",
    department: "Chemical Sciences",
    course: "Industrial Chemistry",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Jesicca Bukola `,
    staffID: "43675",
    email: "jesicabukky@gmail.com",
    level: "Associate Professor",
    department: "Social Sciences",
    course: "Archaelogy",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `James Adeyemi `,
    stafID: "97287",
    email: "jamesadeyemi@gmail.com",
    level: "Junior Lecturer",
    department: "Engineering",
    course: "Architecture",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Tola Cregx `,
    staffID: "39786",
    email: "tolacregx@gmail.com",
    level: "Senior Lecturer",
    department: "Art",
    course: "Celtic Studies",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
  {
    name: `Pem Mayowa `,
    staffID: "14315",
    email: "mayowapem@gmail.com",
    level: "Senior Lecturer",
    department: "Management",
    course: "Accounting & Finance",
    link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
    type: "E - Book",
  },
];

export default data;
