export const data = [
    {
      name: `Temidayo Kukoyi `,
      matricNumber: "011004001",
      level: "200",
      department: "Computer Science",
      course: "Computer Science",
      mark: "65",
      grade: "B",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `James Ubong`,
      matricNumber: "011004604",
      level: "200",
      department: "Computer Science",     
      course: "Computer Science",
      mark: "78",
      grade: "A",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Janet Iron `,
      matricNumber: "011004001",
      level: "200",
      department: "Computer Science",     
      course: "Computer Science",
      mark: "32",
      grade: "E",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Oladipupo Bori `,
      matricNumber: "011004023",
      level: "300",
      department: "Computer Science",      
      course: "Computer Science",
      mark: "28",
      grade: "E",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Towode Ayodele `,
      matricNumber: "011004601",
      level: "200",
      department: "Computer Science",
      course: "Computer Science",
      mark: "90",
      grade: "A",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Temidayo Kukoyi `,
      matricNumber: "011004083",
      level: "400",
      department: "Computer Science",      
      course: "Computer Science",
      mark: "80",
      grade: "A",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Danjuma Iyare `,
      matricNumber: "011004374",
      level: "300",
      department: "Computer Science",      
      course: "Computer Science",
      mark: "20",
      grade: "F",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Ireti Isayemi `,
      matricNumber: "011004001",
      level: "400",
      department: "Computer Science",      
      course: "Mathematics",
      mark: "58",
      grade: "C",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Jesicca Bukola `,
      matricNumber: "011004853",
      level: "200",
      department: "Computer Science",      
      course: "Computer Science",
      mark: "45",
      grade: "D",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `James Adeyemi `,
      matricNumber: "011002403",
      level: "300",
      department: "Computer Science",      
      course: "Computer Science",
      mark: "18",
      grade: "F",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
    {
      name: `Tola Cregx `,
      matricNumber: "011004521",
      level: "300",
      department: "Computer Science",      
      course: "Computer Science",
      mark: "98",
      grade: "A",
      status: "Compulsory",
      link: "https://www.youtube.com/watch?v=efpOA91HaS0&list=RDMM&start_radio=1",
      type: "E - Book",
    },
  ];
  
  export default data;
  